/* generated by rust_qt_binding_generator */
use libc::{c_char, c_ushort, c_int};
use std::slice;
use std::char::decode_utf16;

use std::sync::Arc;
use std::sync::atomic::{AtomicPtr, Ordering};
use std::ptr::null;

use implementation::*;


pub enum QString {}

fn set_string_from_utf16(s: &mut String, str: *const c_ushort, len: c_int) {
    let utf16 = unsafe { slice::from_raw_parts(str, to_usize(len)) };
    let characters = decode_utf16(utf16.iter().cloned())
        .map(|r| r.unwrap());
    s.clear();
    s.extend(characters);
}



fn to_usize(n: c_int) -> usize {
    if n < 0 {
        panic!("Cannot cast {} to usize", n);
    }
    n as usize
}


fn to_c_int(n: usize) -> c_int {
    if n > c_int::max_value() as usize {
        panic!("Cannot cast {} to c_int", n);
    }
    n as c_int
}


pub struct RadicandQObject {}

pub struct RadicandEmitter {
    qobject: Arc<AtomicPtr<RadicandQObject>>,
    rad_changed: extern fn(*mut RadicandQObject),
}

unsafe impl Send for RadicandEmitter {}

impl RadicandEmitter {
    /// Clone the emitter
    ///
    /// The emitter can only be cloned when it is mutable. The emitter calls
    /// into C++ code which may call into Rust again. If emmitting is possible
    /// from immutable structures, that might lead to access to a mutable
    /// reference. That is undefined behaviour and forbidden.
    pub fn clone(&mut self) -> RadicandEmitter {
        RadicandEmitter {
            qobject: self.qobject.clone(),
            rad_changed: self.rad_changed,
        }
    }
    fn clear(&self) {
        let n: *const RadicandQObject = null();
        self.qobject.store(n as *mut RadicandQObject, Ordering::SeqCst);
    }
    pub fn rad_changed(&mut self) {
        let ptr = self.qobject.load(Ordering::SeqCst);
        if !ptr.is_null() {
            (self.rad_changed)(ptr);
        }
    }
}

pub trait RadicandTrait {
    fn new(emit: RadicandEmitter) -> Self;
    fn emit(&mut self) -> &mut RadicandEmitter;
    fn rad(&self) -> u32;
}

#[no_mangle]
pub extern "C" fn radicand_new(
    radicand: *mut RadicandQObject,
    radicand_rad_changed: extern fn(*mut RadicandQObject),
) -> *mut Radicand {
    let radicand_emit = RadicandEmitter {
        qobject: Arc::new(AtomicPtr::new(radicand)),
        rad_changed: radicand_rad_changed,
    };
    let d_radicand = Radicand::new(radicand_emit);
    Box::into_raw(Box::new(d_radicand))
}

#[no_mangle]
pub unsafe extern "C" fn radicand_free(ptr: *mut Radicand) {
    Box::from_raw(ptr).emit().clear();
}

#[no_mangle]
pub unsafe extern "C" fn radicand_rad_get(ptr: *const Radicand) -> u32 {
    (&*ptr).rad()
}

pub struct TimeQObject {}

pub struct TimeEmitter {
    qobject: Arc<AtomicPtr<TimeQObject>>,
    hour_changed: extern fn(*mut TimeQObject),
    minute_changed: extern fn(*mut TimeQObject),
    second_changed: extern fn(*mut TimeQObject),
}

unsafe impl Send for TimeEmitter {}

impl TimeEmitter {
    /// Clone the emitter
    ///
    /// The emitter can only be cloned when it is mutable. The emitter calls
    /// into C++ code which may call into Rust again. If emmitting is possible
    /// from immutable structures, that might lead to access to a mutable
    /// reference. That is undefined behaviour and forbidden.
    pub fn clone(&mut self) -> TimeEmitter {
        TimeEmitter {
            qobject: self.qobject.clone(),
            hour_changed: self.hour_changed,
            minute_changed: self.minute_changed,
            second_changed: self.second_changed,
        }
    }
    fn clear(&self) {
        let n: *const TimeQObject = null();
        self.qobject.store(n as *mut TimeQObject, Ordering::SeqCst);
    }
    pub fn hour_changed(&mut self) {
        let ptr = self.qobject.load(Ordering::SeqCst);
        if !ptr.is_null() {
            (self.hour_changed)(ptr);
        }
    }
    pub fn minute_changed(&mut self) {
        let ptr = self.qobject.load(Ordering::SeqCst);
        if !ptr.is_null() {
            (self.minute_changed)(ptr);
        }
    }
    pub fn second_changed(&mut self) {
        let ptr = self.qobject.load(Ordering::SeqCst);
        if !ptr.is_null() {
            (self.second_changed)(ptr);
        }
    }
}

pub trait TimeTrait {
    fn new(emit: TimeEmitter) -> Self;
    fn emit(&mut self) -> &mut TimeEmitter;
    fn hour(&self) -> u32;
    fn minute(&self) -> u32;
    fn second(&self) -> u32;
}

#[no_mangle]
pub extern "C" fn time_new(
    time: *mut TimeQObject,
    time_hour_changed: extern fn(*mut TimeQObject),
    time_minute_changed: extern fn(*mut TimeQObject),
    time_second_changed: extern fn(*mut TimeQObject),
) -> *mut Time {
    let time_emit = TimeEmitter {
        qobject: Arc::new(AtomicPtr::new(time)),
        hour_changed: time_hour_changed,
        minute_changed: time_minute_changed,
        second_changed: time_second_changed,
    };
    let d_time = Time::new(time_emit);
    Box::into_raw(Box::new(d_time))
}

#[no_mangle]
pub unsafe extern "C" fn time_free(ptr: *mut Time) {
    Box::from_raw(ptr).emit().clear();
}

#[no_mangle]
pub unsafe extern "C" fn time_hour_get(ptr: *const Time) -> u32 {
    (&*ptr).hour()
}

#[no_mangle]
pub unsafe extern "C" fn time_minute_get(ptr: *const Time) -> u32 {
    (&*ptr).minute()
}

#[no_mangle]
pub unsafe extern "C" fn time_second_get(ptr: *const Time) -> u32 {
    (&*ptr).second()
}
