/* generated by rust_qt_binding_generator */
#ifndef BINDINGS_H
#define BINDINGS_H

#include <QtCore/QObject>
#include <QtCore/QAbstractItemModel>

class Radicand;

class Radicand : public QObject
{
    Q_OBJECT
public:
    class Private;
private:
    Private * m_d;
    bool m_ownsPrivate;
    Q_PROPERTY(QString param READ param WRITE setParam NOTIFY paramChanged FINAL)
    Q_PROPERTY(QString result READ result NOTIFY resultChanged FINAL)
    explicit Radicand(bool owned, QObject *parent);
public:
    explicit Radicand(QObject *parent = nullptr);
    ~Radicand();
    QString param() const;
    void setParam(const QString& v);
    QString result() const;
Q_SIGNALS:
    void paramChanged();
    void resultChanged();
};
#endif // BINDINGS_H
